config/routes.rb
Ilbirrone::Application.routes.draw do

  root to: 'home_page#show'

  scope(:path_names => { :new => "nuova", :edit => "modifica" }) do
    resources :pubs, path: 'birrerie' do
      collection do
        get 'cerca', to: 'pubs#search', as: :search
        get 'birrerie-nei-dintorni', to: 'geolocation#nearby', as: :nearby
        get :nearest, to: 'geolocation#nearest_pub'
        get 'recensioni-recenti-birrerie-pub', to: 'pubs#recent_reviews', as: :recent_reviews
        get 'recensioni-recenti-brewpub', to: 'brewpubs#recent_reviews', as: :brewpub_recent_reviews
        get 'birrerie-pub-curiosi', to: 'pubs#curious', as: :curious
        get 'scrivi-recensione-birreria', to: 'pubs#select_for_review', as: :select_for_review
        get 'province-italiane', to: 'pubs#provinces', as: :provinces
        post :send_changes, to: 'changes#send_pub_changes'
      end
      member do
        get :webmaster
        get :change, to: 'changes#pub'
      end
    end
    resources :beers, path: 'birre'
    resources :reviews, path: 'recensioni'
    resources :beer_reviews, path: 'recensioni-birre'

    namespace :admin do
      resources :pubs, path: 'birrerie' do
        member do
          post 'approve'
          get :edit_location
        end
      end
      get 'statistiche', to: 'statistics#index', as: :statistics
      resources :users, path: 'utenti'
      resources :beers, path: 'birre'
      resources :pub_events, path: 'eventi-birrerie'
      resources :public_events, path: 'eventi-pubblici'
      resources :events, path: 'eventi', only: [:index, :destroy]
      resources :reviews, path: 'recensioni'
      resources :comments
      resources :pre_registrations
      resources :visitors, only: [:index]
    end
  end

  resources :comments, only: [:destroy] do
    collection do
      post :upload
      post :upload_avatar
      post :upload_comment
      post :upload_user_comment
    end
  end

  get "microbirrifici" => "pubs#microbreweries", as: :microbreweries
  get "brewpub" => "brewpubs#index", as: :brewpub

  scope(:path_names => { :new => "nuovo", :edit => "modifica" }) do
    devise_for :users, 
      :path => "utenti", 
      :path_names => { 
        :sign_in => 'accedi', 
        :sign_out => 'esci', 
        :sign_up => 'registrati' },
      :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }

    resources :events, path: 'eventi', only: [:index, :show] do
      collection do
        get 'seleziona-tipo-evento', to: 'events#select_type', as: :select_type
      end
    end

    resources :public_events, path: 'eventi-pubblici', only: [:new, :create]
    resources :public_events, path: 'eventi', only: [:show]
    resources :pub_events, path: 'eventi-birrerie', only: [:new, :create]
    resources :pub_events, path: 'eventi', only: [:show]
  end

  resources :users, path: 'utenti', only: [:show, :index] do
    collection do
      get :search, to: 'users#search'
    end
  end

  resource :informations, path: 'informazioni', only: [] do
    get 'privacy', to: 'informations#privacy', as: :privacy
    get 'chi-siamo', to: 'informations#who_we_are', as: :who_we_are
  end
  
  resource :contact_us, path: 'contattaci', only: [:new, :create]

  get 'cosa-e-la-birra', to: 'beer_pages#whatis', as: :what_is_beer
  get 'birra-artigianale', to: 'beer_pages#craft_beer', as: :craft_beer
  get 'storia-della-birra', to: 'beer_pages#history', as: :history
  get 'oktoberfest', to: 'beer_pages#oktoberfest', as: :oktoberfest

  get 'sfide', to: 'achievements#index', as: :achievements

  get 'cerca', to: 'search#index', as: :search
  post 'cerca', to: 'search#autocomplete', as: :autocomplete
  post 'cerca-birrerie-nuovo-evento', to: 'search#autocomplete_pub_new_event', as: :autocomplete_pub_new_event
  post 'cerca-birrerie-nuova-recensione', to: 'search#autocomplete_pub_new_review', as: :autocomplete_pub_new_review

  get 'guida-recensione', to: 'reviews#guide', as: :review_guide
  get 'come-inserire-una-recensione', to: 'reviews#how_to_create', as: :review_how_to_create

  resources :homebrewers, path: 'homebrewer', only: [] do
    collection do
      get :pre_registration, path: 'preiscriviti'
      post :invite
    end
  end
  
  resources :pre_registrations

  resources :visitors, only: [] do
    collection do
      get :visit_pub
      post :geolocated_visit_pub
    end
  end

  resources :notifications
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def show
    @recent_events = EventQuery.new.first(3)
    @popular_pubs = Ranking.popular_pubs
    @recent_pubs = PubQuery.recents_with_cover(6)
    @notifications = Notification.timeline(10)
  end
end

app/views/home_page/_activity_separator.html.erb
<li>
  <div class="clearfix"></div>
  <hr class="activity_separator">
</li>

app/views/home_page/_pub.html.erb
<% pub_presenter = PubPresenter.create(pub, self) %>
<div class="col-md-4">
    <div class="recent-pub-box">
        <%= link_to pub_path(pub) do %>
          <%= pub_presenter.photo_tag %>
        <% end %>
        <h4><%= link_to pub_presenter.name, pub_path(pub) %></h4>
        <i class="fa fa-map-marker"></i>
        <%= pub_presenter.city_with_province %>
    </div>
</div>

app/views/home_page/_recent_event.html.erb
<li class="recent-event">
  <div class="row">
    <div class="col-md-4 col-xs-4">
      <% presenter = EventPresenter.create(recent_event, self) %>
      <%= link_to event_path(recent_event) do %>
        <%= presenter.photo_tag %>
      <% end %>
    </div>
    <div class="col-md-8 col-xs-8">
      <span class="text-muted">
        <i class="fa fa-calendar"></i>
        <%= presenter.when %>
      </span><br>
      <h4><%= presenter.title %></h4>
      <p><%= presenter.short_description %></p>
      <p>
        <span class="text-muted">
          <i class="fa fa-map-marker"></i>
          <%= recent_event.location %> - <%= recent_event.city %>
        </span>
      </p>
      <p>
        <%= link_to "Maggiori informazioni...", event_path(recent_event) %>
      </p>
    </div>
  </div>
</li>

app/views/home_page/_recent_images.html.erb
<% carousel = CarouselPresenter.new(pubs, self) %>

<div id="pubsCarousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <%= carousel.render_indicators('pubsCarousel') %>
    </ol>
    <div class="carousel-inner">
        <%= carousel.render_items %>
    </div>
    <a class="left carousel-control" href="#pubsCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#pubsCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
    </a>      
</div>

<%= javascript_tag do %>
  $('.carousel').carousel();
<% end %>

app/views/home_page/_reviews.html.erb
<p><b>Nuove Recensioni</b></p>
<% for review in reviews %>
    <% pub = review.pub %>
    <p>
        <%= link_to pub.name, pub_path(pub) -%> - <%= pub.city %><br>
        <%= small_rating_tag(review.rating) %>
        di <%= link_to review.user.username, user_path(review.user) -%>
    </p>
<% end %>

app/views/home_page/show.html.erb
<% content_for :title do %><%= t('.title') -%><% end %>
<% content_for :meta_description, t('.description') %>
<div class="row">
  <div class="col-md-12">

    <% unless signed_in? %>
    <div class="jumbotron">
      <p class="big-text"><%= t('.description') %></p>
      <%= link_to "Diventa un Birronauta!", new_user_registration_path, class: 'btn btn-primary btn-lg' %>
    </div>
    <% end %>

    <div class="home-box">
      <h3>I più visti dai Birronauti</h3>
      <%= render partial: 'recent_images', locals: {pubs: @popular_pubs} %>
    </div>
    
    <div class="row">
      
      <div class="col-md-5">
        <h3>Novità dai Birronauti</h3>
        <%= render partial: 'notifications/notifications', locals: { notifications: @notifications } %>
        <div class="notifications-link text-right">
          <%= link_to "Vedi tutte le novità", notifications_path %>
          <%= link_to "&raquo;".html_safe, notifications_path %>
        </div>
        <div class="clearfix"></div>
      </div>

      <div class="col-md-7">
        <div class="home-box">
          <h3>Eventi da non perdere</h3>
          <ul class="list-unstyled">
            <%= render partial: 'recent_event', collection: @recent_events, spacer_template: "activity_separator" %>
          </ul>
          <%= link_to "Vedi tutti gli eventi", events_path, class: 'pull-right' %>
          <div class="clearfix"></div>
        </div>
        <div class="cloud-box">
          <h3>Birrerie nella tua città</h3>
          <%= render partial: 'pubs/cloud' %>
        </div>
        <div class="home-box">

          <h3>Nuove Segnalazioni</h3>
          <% @recent_pubs.in_groups_of(3, false) do |pubs| %>
            <div class="row">
              <%= render partial: 'pub', collection: pubs %>
            </div>
          <% end %>
          <%= link_to "Vedi tutte le Birrerie", pubs_path, class: 'pull-right' %>
          <div class="clearfix"></div>

        </div>

        <div class="cloud-box">
          <h3>Birrerie nel mondo</h3>
          <%= render partial: 'pubs/world_cloud' %>
        </div>

        <div class="facebook-box">
          <%= render partial: 'shared/facebook_with_photos' %>
        </div>

      </div>
    </div>

    <div class="row">
      <div class="col-md-8">
      </div>
      <div class="col-md-4">
      </div>
    </div>

  </div>
</div>