config/routes.rb
Ilbirrone::Application.routes.draw do

  root to: 'home_page#show'

  scope(:path_names => { :new => "nuova", :edit => "modifica" }) do
    resources :pubs, path: 'birrerie' do
      collection do
        get 'cerca', to: 'pubs#search', as: :search
        get 'birrerie-nei-dintorni', to: 'geolocation#nearby', as: :nearby
        get :nearest, to: 'geolocation#nearest_pub'
        get 'recensioni-recenti-birrerie-pub', to: 'pubs#recent_reviews', as: :recent_reviews
        get 'recensioni-recenti-brewpub', to: 'brewpubs#recent_reviews', as: :brewpub_recent_reviews
        get 'birrerie-pub-curiosi', to: 'pubs#curious', as: :curious
        get 'scrivi-recensione-birreria', to: 'pubs#select_for_review', as: :select_for_review
        get 'province-italiane', to: 'pubs#provinces', as: :provinces
        post :send_changes, to: 'changes#send_pub_changes'
      end
      member do
        get :webmaster
        get :change, to: 'changes#pub'
      end
    end
    resources :beers, path: 'birre'
    resources :reviews, path: 'recensioni'
    resources :beer_reviews, path: 'recensioni-birre'

    namespace :admin do
      resources :pubs, path: 'birrerie' do
        member do
          post 'approve'
          get :edit_location
        end
      end
      get 'statistiche', to: 'statistics#index', as: :statistics
      resources :users, path: 'utenti'
      resources :beers, path: 'birre'
      resources :pub_events, path: 'eventi-birrerie'
      resources :public_events, path: 'eventi-pubblici'
      resources :events, path: 'eventi', only: [:index, :destroy]
      resources :reviews, path: 'recensioni'
      resources :comments
      resources :pre_registrations
      resources :visitors, only: [:index]
    end
  end

  resources :comments, only: [:destroy] do
    collection do
      post :upload
      post :upload_avatar
      post :upload_comment
      post :upload_user_comment
    end
  end

  get "microbirrifici" => "pubs#microbreweries", as: :microbreweries
  get "brewpub" => "brewpubs#index", as: :brewpub

  scope(:path_names => { :new => "nuovo", :edit => "modifica" }) do
    devise_for :users, 
      :path => "utenti", 
      :path_names => { 
        :sign_in => 'accedi', 
        :sign_out => 'esci', 
        :sign_up => 'registrati' },
      :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }

    resources :events, path: 'eventi', only: [:index, :show] do
      collection do
        get 'seleziona-tipo-evento', to: 'events#select_type', as: :select_type
      end
    end

    resources :public_events, path: 'eventi-pubblici', only: [:new, :create]
    resources :public_events, path: 'eventi', only: [:show]
    resources :pub_events, path: 'eventi-birrerie', only: [:new, :create]
    resources :pub_events, path: 'eventi', only: [:show]
  end

  resources :users, path: 'utenti', only: [:show, :index] do
    collection do
      get :search, to: 'users#search'
    end
  end

  resource :informations, path: 'informazioni', only: [] do
    get 'privacy', to: 'informations#privacy', as: :privacy
    get 'chi-siamo', to: 'informations#who_we_are', as: :who_we_are
  end
  
  resource :contact_us, path: 'contattaci', only: [:new, :create]

  get 'cosa-e-la-birra', to: 'beer_pages#whatis', as: :what_is_beer
  get 'birra-artigianale', to: 'beer_pages#craft_beer', as: :craft_beer
  get 'storia-della-birra', to: 'beer_pages#history', as: :history
  get 'oktoberfest', to: 'beer_pages#oktoberfest', as: :oktoberfest

  get 'sfide', to: 'achievements#index', as: :achievements

  get 'cerca', to: 'search#index', as: :search
  post 'cerca', to: 'search#autocomplete', as: :autocomplete
  post 'cerca-birrerie-nuovo-evento', to: 'search#autocomplete_pub_new_event', as: :autocomplete_pub_new_event
  post 'cerca-birrerie-nuova-recensione', to: 'search#autocomplete_pub_new_review', as: :autocomplete_pub_new_review

  get 'guida-recensione', to: 'reviews#guide', as: :review_guide
  get 'come-inserire-una-recensione', to: 'reviews#how_to_create', as: :review_how_to_create

  resources :homebrewers, path: 'homebrewer', only: [] do
    collection do
      get :pre_registration, path: 'preiscriviti'
      post :invite
    end
  end
  
  resources :pre_registrations

  resources :visitors, only: [] do
    collection do
      get :visit_pub
      post :geolocated_visit_pub
    end
  end

  resources :notifications
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    if (search_text.nil? || search_text.size < 3)
      redirect_to root_path, flash: { error: t('search.index.invalid_search') }
      return
    end

    @pubs = PubQuery.new.search(search_text)
    @beers = BeerQuery.new.search(search_text)
    @search_text = search_text 
  end

  def autocomplete
    render json: ( cities(params[:query]) + beers(params[:query]) + pubs(params[:query]) ).to_json
  end
  
  def autocomplete_pub_new_event
    render json: (pubs_with_new_event_path(params[:query])).to_json
  end

  def autocomplete_pub_new_review
    render json: (pubs_with_new_review_path(params[:query])).to_json
  end

  def cities(query)
    Place.where_city(query).map {|city| [ view_context.format_city(city), pubs_path(provincia: city[0])]}
  end

  def beers(query)
    BeerQuery.new.search_first(query, 20).map {|beer| ["Birra - #{beer.name} - #{beer.pub.name}", beer_path(beer)]}
  end

  def pubs(query)
    PubQuery.new.search_first(query, 20).map {|pub| ["#{pub.pub_type} - #{pub.name} - #{pub.city}", pub_path(pub)]}
  end

  def pubs_with_new_event_path(query)
    PubQuery.new.search_first(query, 20).map {|pub| ["#{pub.pub_type} - #{pub.name} - #{pub.city}", new_pub_event_path(pub_id: pub.id)]}
  end
  
  def pubs_with_new_review_path(query)
    PubQuery.new.search_first(query, 20).map {|pub| ["#{pub.pub_type} - #{pub.name} - #{pub.city}", new_review_path(pub_id: pub.id)]}
  end

  def search_text
    params[:text]
  end
end

app/views/search/_beers.html.erb
<h4>Birre Artigianali</h4>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= Beer.human_attribute_name(:name) -%></th>
      <th>Prodotta da</th>
      <th><%= Beer.human_attribute_name(:alcohol_by_volume) -%></th>
      <th><%= Beer.human_attribute_name(:color) -%></th>
      <th>Giudizio</th>
    </tr>
  </thead>
  <tbody>
    <% for beer in @beers.map {|beer| BeerPresenter.new(beer, self)} %>
      <tr>
        <td><%= link_to beer.name, beer_path(beer.model) -%></td>
        <td><%= link_to beer.pub.name, pub_path(beer.pub) -%></td>
        <td><%= beer.alcohol_by_volume -%></td>
        <td><%= beer.color -%></td>
        <td><%= small_rating_tag beer.rating %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/search/_no_results.html.erb
<p><b>La ricerca non ha prodotto risultati. Prova un'altra ricerca o aggiungi una nuova birreria, brewpub o microbirrificio, cliccando sotto:</b></p>

app/views/search/_pubs.html.erb
<h4>Birrerie, Brewpub e Microbirrifici</h4>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= Pub.human_attribute_name(:name) %></th>
      <th><%= Pub.human_attribute_name(:city) %></th>
      <th><%= Pub.human_attribute_name(:pub_type) %></th>
      <th><%= Pub.human_attribute_name(:rating) %></th>
    </tr>
  </thead>
  <tbody>
    <% pubs.each do |pub| %>
      <tr>
        <td><%= link_to pub.name, pub_path(pub) %></td>
        <td><%= pub.city_with_province -%></td>
        <td><%= pub.pub_type -%></td>
        <td><%= small_rating_tag pub.rating %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/search/_with_results.html.erb
<p>Non hai trovato quello che cercavi? Puoi effettuare una nuova ricerca o segnalare un nuovo locale cliccando:</p>

app/views/search/index.html.erb
<%= render_breadcrumb(@search_text) %>
<div class="page-title">
  <h1>Risultati per "<%= @search_text -%>"</h1>
</div>
<% presenter = SearchPresenter.new(@beers, @pubs) %>
<%= presenter.render(self) %>
<%= presenter.render_add_pub_invitation(self) %>
<%= link_to t("helpers.links.add_pub"), new_pub_path, :class => 'btn btn-primary' %>