config/routes.rb
Ilbirrone::Application.routes.draw do

  root to: 'home_page#show'

  scope(:path_names => { :new => "nuova", :edit => "modifica" }) do
    resources :pubs, path: 'birrerie' do
      collection do
        get 'cerca', to: 'pubs#search', as: :search
        get 'birrerie-nei-dintorni', to: 'geolocation#nearby', as: :nearby
        get :nearest, to: 'geolocation#nearest_pub'
        get 'recensioni-recenti-birrerie-pub', to: 'pubs#recent_reviews', as: :recent_reviews
        get 'recensioni-recenti-brewpub', to: 'brewpubs#recent_reviews', as: :brewpub_recent_reviews
        get 'birrerie-pub-curiosi', to: 'pubs#curious', as: :curious
        get 'scrivi-recensione-birreria', to: 'pubs#select_for_review', as: :select_for_review
        get 'province-italiane', to: 'pubs#provinces', as: :provinces
        post :send_changes, to: 'changes#send_pub_changes'
      end
      member do
        get :webmaster
        get :change, to: 'changes#pub'
      end
    end
    resources :beers, path: 'birre'
    resources :reviews, path: 'recensioni'
    resources :beer_reviews, path: 'recensioni-birre'

    namespace :admin do
      resources :pubs, path: 'birrerie' do
        member do
          post 'approve'
          get :edit_location
        end
      end
      get 'statistiche', to: 'statistics#index', as: :statistics
      resources :users, path: 'utenti'
      resources :beers, path: 'birre'
      resources :pub_events, path: 'eventi-birrerie'
      resources :public_events, path: 'eventi-pubblici'
      resources :events, path: 'eventi', only: [:index, :destroy]
      resources :reviews, path: 'recensioni'
      resources :comments
      resources :pre_registrations
      resources :visitors, only: [:index]
    end
  end

  resources :comments, only: [:destroy] do
    collection do
      post :upload
      post :upload_avatar
      post :upload_comment
      post :upload_user_comment
    end
  end

  get "microbirrifici" => "pubs#microbreweries", as: :microbreweries
  get "brewpub" => "brewpubs#index", as: :brewpub

  scope(:path_names => { :new => "nuovo", :edit => "modifica" }) do
    devise_for :users, 
      :path => "utenti", 
      :path_names => { 
        :sign_in => 'accedi', 
        :sign_out => 'esci', 
        :sign_up => 'registrati' },
      :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }

    resources :events, path: 'eventi', only: [:index, :show] do
      collection do
        get 'seleziona-tipo-evento', to: 'events#select_type', as: :select_type
      end
    end

    resources :public_events, path: 'eventi-pubblici', only: [:new, :create]
    resources :public_events, path: 'eventi', only: [:show]
    resources :pub_events, path: 'eventi-birrerie', only: [:new, :create]
    resources :pub_events, path: 'eventi', only: [:show]
  end

  resources :users, path: 'utenti', only: [:show, :index] do
    collection do
      get :search, to: 'users#search'
    end
  end

  resource :informations, path: 'informazioni', only: [] do
    get 'privacy', to: 'informations#privacy', as: :privacy
    get 'chi-siamo', to: 'informations#who_we_are', as: :who_we_are
  end
  
  resource :contact_us, path: 'contattaci', only: [:new, :create]

  get 'cosa-e-la-birra', to: 'beer_pages#whatis', as: :what_is_beer
  get 'birra-artigianale', to: 'beer_pages#craft_beer', as: :craft_beer
  get 'storia-della-birra', to: 'beer_pages#history', as: :history
  get 'oktoberfest', to: 'beer_pages#oktoberfest', as: :oktoberfest

  get 'sfide', to: 'achievements#index', as: :achievements

  get 'cerca', to: 'search#index', as: :search
  post 'cerca', to: 'search#autocomplete', as: :autocomplete
  post 'cerca-birrerie-nuovo-evento', to: 'search#autocomplete_pub_new_event', as: :autocomplete_pub_new_event
  post 'cerca-birrerie-nuova-recensione', to: 'search#autocomplete_pub_new_review', as: :autocomplete_pub_new_review

  get 'guida-recensione', to: 'reviews#guide', as: :review_guide
  get 'come-inserire-una-recensione', to: 'reviews#how_to_create', as: :review_how_to_create

  resources :homebrewers, path: 'homebrewer', only: [] do
    collection do
      get :pre_registration, path: 'preiscriviti'
      post :invite
    end
  end
  
  resources :pre_registrations

  resources :visitors, only: [] do
    collection do
      get :visit_pub
      post :geolocated_visit_pub
    end
  end

  resources :notifications
end

app/models/pub.rb
class Pub < ActiveRecord::Base
  include FriendlyId
  include Cover
  include  UserPointsUpdate  
  
  geocoded_by :full_address

  attr_accessible :address, :city, :name, :province, :postcode, :phone, :email, :website, 
    :closing_days, :status, :description, :pub_type, :region, :latitude, :longitude, :country
  has_many :reviews, -> { order(date: :desc) }, :dependent => :destroy
  has_many :beers, -> { order(:name) }, :dependent => :destroy
  has_many :events, class_name: "PubEvent", :dependent => :destroy
  has_many :comments, -> { order(created_at: :desc) }, as: :commentable, :dependent => :destroy
  has_many :visitors, :dependent => :destroy
  belongs_to :user

  friendly_id :formatted_friendly_id, use: [:slugged, :finders]

  validates :name, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :province, presence: true
  validates :user, presence: true

  def images
    covers
  end

  def full_address
    "#{self.address} - #{self.postcode} #{self.city_with_province}"
  end

  def city_with_province
    return self.city if city.downcase == province.downcase
    "#{self.city} (#{self.province})"
  end

  def rating
    Rating.calculate(reviews)
  end

  def formatted_friendly_id
    "#{self.name} #{self.city}"
  end

  def submit!
    self.status = 'submitted'
    save
  end

  def approved?
    self.status == 'approved'
  end

  def approve!
    self.status = 'approved'
    save
  end

  def set_location(latitude, longitude)
    self.latitude = latitude
    self.longitude = longitude
  end

  def has_coordinates?
    self.latitude.present? && self.longitude.present?
  end

  def photo_description
    "#{pub_type} #{name}"
  end

  def default_photo
    'no-photo.jpg'
  end

  def visitor_count
    anonymous_visits = visitors.select {|v| v.confirmed? && v.user.nil? }.size
    visits = visitors.select {|v| v.confirmed? && v.user.present? }.group_by(&:user).size
    anonymous_visits + visits
  end

  def visitor?(user)
    return false if user.nil?
    visitors.select { |v| v.confirmed? && v.user.present? && v.user.id == user.id }.present?
  end
end

app/controllers/admin/pubs_controller.rb
require 'map'

module Admin
  class PubsController < AdminController
    
    def index
      @pubs = Pub.paginate(:page => params[:page], :per_page => 50).order(created_at: :desc)
    end

    def show
      @pub = Pub.find(params[:id])
    end
    
    def new
      @pub = Pub.new
    end

    def edit
      @pub = Pub.find(params[:id])
    end

    def edit_location
      @pub = Pub.find(params[:id])
    end

    def update
      @pub = Pub.find(params[:id])
      if @pub.update_attributes(params[:pub])
        flash[:success] = "Birreria #{@pub.name} aggiornata"
        redirect_to admin_pub_path(@pub)
      else
        render 'edit'
      end      
    end

    def create
      @pub = Pub.new(params[:pub])
      @pub.user = current_user 
      Map.geocode(@pub)
      if @pub.approve!
        Notification.notify_pub_approval(@pub)
        redirect_to admin_pubs_path
      else
        render 'new'
      end
    end 


    def destroy
      @pub = Pub.find(params[:id])
      @pub.destroy
      redirect_to admin_pubs_path, flash: {success: "Hai eliminato #{@pub.name}"}
    end

    def approve
      @pub = Pub.find(params[:id])
      @pub.approve!
      Notification.notify_pub_approval(@pub)
      redirect_to admin_pubs_path, flash: {success: "Hai approvato #{@pub.name}"}
    end
  end
end

app/controllers/pubs_controller.rb
require 'pub_query'
require 'map'

class PubsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create]

  def new
    @pub = Pub.new
    @pub.pub_type = params[:pub_type] || 'Birreria'
  end

  def create
    @pub = Pub.new(params[:pub])
    @pub.user = current_user
    Map.geocode(@pub)

    if @pub.submit!
      redirect_to pub_path(@pub), flash: {success: t('pubs.create.submitted')}
    else
      render 'new'
    end
  end 

  def show
    @pub = PubQuery.find(params[:id])
  end

  def search
    redirect_to pubs_path(provincia: params[:pub][:location]), status: 301
  end

  def index
    IndexPubsHandler.execute(self, params[:provincia], params[:show])
  end

  def microbreweries
    if params[:region].present?
      @microbreweries = PubQuery.new.microbreweries(params[:region])
    else
      @microbreweries = PubQuery.new.microbreweries_by_region
    end
  end

  def curious
    @pubs = PubQuery.curious
  end

  def recent_reviews
    @pubs = PubQuery.new.recents_with_review(15, ['Brewpub', 'Birreria'])
  end

  def webmaster
    @pub = Pub.find(params[:id])
  end

  def select_for_review
  end

  def provinces
    @provinces = PubQuery.new.provinces_with_count(['Brewpub', 'Birreria'])
  end
end

app/helpers/pubs_helper.rb
module PubsHelper
  def pub_cloud_link(province, weight)
    link_to province, pubs_path(provincia: province), class: "cloud_#{weight}"
  end
  
  def brewpub_cloud_link(province, weight)
    link_to province, brewpub_path(provincia: province), class: "cloud_#{weight}"
  end

  def pub_owner?
    current_user && current_user.admin?
  end

  def webmaster_code(pub, image_name, width, height)
    link_to pub_url(pub) do
      tag :img, 
        src: URI.join(root_url, image_path(image_name)), 
        alt: 'Segnalato su Beerky', 
        width: width, height: height
    end
  end

  def format_location(pub)
    return "(#{pub.latitude}, #{pub.longitude})" if pub.latitude.present?
    "non geocalizzato"
  end

  def marker_image(pub)
    if pub.reviews.size > 0
      return URI.join(root_url, image_path('marker-con-recensioni.png'))
    end
    return URI.join(root_url, image_path('marker.png'))
  end

  def user_with_points(user)
      [
        link_to(user.username, user_path(user)), tag(:br), 
        user.points, "&nbsp;", t("point", count: user.points)
      ].join.html_safe
  end
end

app/views/admin/pubs/edit.html.erb
<h1>Modifica <%= @pub.pub_type %> <%= @pub.name %> - <%= @pub.city %></h1>
<%= render partial: 'shared/pub_form', locals: {pub: @pub, options: {url: admin_pub_path}} %>

app/views/admin/pubs/edit_location.html.erb
<h1>Modifica posizione <%= @pub.name %></h1>
<%= simple_form_for(@pub, url: admin_pub_path) do |f| %>
  <%= render 'shared/error_messages', f: f %>
  <%= f.input :latitude %>
  <%= f.input :longitude %>
  <%= f.submit t('helpers.links.save'), class: 'btn btn-primary' %>
<% end %>

app/views/admin/pubs/index.html.erb
<%- model_class = Pub.new.class -%>
<%= render_breadcrumb [Breadcrumb.new('Statistiche', admin_statistics_path), Breadcrumb.new('Birrerie')] %>
<h1><%= model_class.count -%> Birrerie inserite <%= PubQuery.new.to_approve_count -%> da approvare</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th>Birronauta</th>
      <th>Comandi</th>
    </tr>
  </thead>
  <tbody>
    <% @pubs.each do |pub| %>
      <tr>
        <td><%= link_to pub.name, pub_path(pub) %></td>
        <td><%= pub.full_address %></td>
        <td><%= pub.email %></td>
        <td><%= link_to pub.user.username, user_path(pub.user) %></td>
        <td>
          <%= link_to t("helpers.links.destroy"), 
                  admin_pub_path(pub), 
                  method: :delete, 
                  data: { confirm: t("helpers.links.confirm")}, 
                  class: 'btn btn-mini btn-warning' -%>
        </td>
        <td>
          <%= link_to t("helpers.links.edit"),
                edit_admin_pub_path(pub),
                class: 'btn btn-mini' -%>
        </td>
        <td>
          <%= link_to(t("helpers.links.approve"), 
                  approve_admin_pub_path(pub), 
                  method: :post, 
                  data: { confirm: t("helpers.links.confirm")}, 
                  class: 'btn btn-mini btn-primary') unless pub.approved? -%> 
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to t("helpers.links.new"), new_admin_pub_path, :class => 'btn btn-primary' %>
<%= will_paginate @pubs, :renderer => BootstrapPagination::Rails %>

app/views/admin/pubs/new.html.erb
<h1>Nuova Segnalazione</h1>
<%= render partial: 'shared/pub_form', locals: {pub: @pub, options: {url: admin_pubs_path}} %>

app/views/admin/pubs/show.html.erb
<%= render_breadcrumb [Breadcrumb.new("Birrerie", admin_pubs_path), Breadcrumb.new(@pub.name, pub_path(@pub)), Breadcrumb.new("Pannello di controllo")] %>
<h1>Pannello di controllo <%= @pub.name -%></h1>
<p><%= format_location(@pub) %></p>
<div class="row">
  <div class="col-md-3">
    <div class="pub-owner">
        <p>
          <%= link_to "Modifica dati #{@pub.pub_type}", edit_admin_pub_path(@pub), class: "btn btn-danger" %>
        </p>
        <p>
        <%= link_to(t("helpers.links.approve"), 
                approve_admin_pub_path(@pub), 
                method: :post, 
                data: { confirm: t("helpers.links.confirm")}, 
                class: 'btn btn-mini btn-primary') unless @pub.approved? %> 
        </p>
        <p>
          <%= link_to("Modifica posizione", edit_location_admin_pub_path(@pub), class: 'btn') %>   
        </p>
    </div>
  </div>
  <div class="col-md-9">
    <h2>Birre</h2>
    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= Beer.human_attribute_name(:name) %></th>
          <th><%= Beer.human_attribute_name(:alcohol_by_volume) %></th>
          <th><%= Beer.human_attribute_name(:color) %></th>
          <th>Comandi</th>
        </tr>
      </thead>
      <tbody>
      <% @pub.beers.each do |beer| %>
        <tr>
          <td><%= link_to beer.name, beer_path(beer) -%></td>
          <td><%= beer.alcohol_by_volume -%></td>
          <td><%= beer.color -%></td>
          <td><%= link_to t("helpers.links.destroy"), 
                    admin_beer_path(beer), 
                    method: :delete, 
                    data: { confirm: t("helpers.links.confirm")}, 
                    class: 'btn btn-mini btn-warning' %>
              <%= link_to t("helpers.links.edit"),
                  edit_admin_beer_path(beer),
                  class: 'btn btn-mini' %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>